### ISSUE TITLE
floating label problem in ion-select and ion-datetime

### ISSUE THREAD

**Issue by Balaraju1** [ionic-team/ionic-conference-app#614] opened 2018-08-13 13:13 UTC
ion-select and ion-datetime floating label not working in ionic 4 beta 2. 
```
<ion-item>
<ion-label position="floating">Label :</ion-label>
<ion-select>
<ion-option-select></ion-option-select>
<ion-option-select></ion-option-select>
<ion-option-select></ion-option-select>
</ion-select>
</ion-item>

<ion-item>
<ion-label position="floating">Label :</ion-label>
<ion-datetime></ion-datetime>
</ion-item>
```
![image](https://user-images.githubusercontent.com/20854774/44027519-652e3a4e-9f14-11e8-8b3d-f43ffaebd5b8.png)

**Comment by brandyscarney** [comment] 2018-08-13 15:30
Thanks for the issue! Since this is not a problem specific to the conference app, I am going to close it as a duplicate of https://github.com/ionic-team/ionic/issues/15140. Please follow that issue for updates, thanks!

**Closed by brandyscarney** 2018-08-13 15:30 UTC
