### ISSUE TITLE
It doesn't work emulating or building android

### ISSUE THREAD

**Issue by razzdrawon** [ionic-team/ionic-conference-app#409] opened 2017-05-30 01:27 UTC
Im trying to emulate or build directly to an android device or emulator and when run: 
"ionic cordova build android" it works and says "BUILD SUCCESSFUL" but when I try installing in a device it fails.

Also when I run "ionic cordova emulate android", it bring the emulator to the front and starts an app but it stays in blank.

Can anybody help me?

**Comment by razzdrawon** [comment] 2017-05-30 01:34
I only clone the repo, added android platform, build android and emulate android but it fails.
Also I have downloaded another starters as "tabs" and "blank" and they run fine, conference doesn't.

**Comment by mautematico** [comment] 2017-05-31 16:45
Please copy-paste the commands you are using while building.
Also please copy-paste `ionic info` output.

**Comment by razzdrawon** [comment] 2017-06-01 04:19
Hi, 
Thanks for answering.

My ionic info:

```
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : OS X El Capitan
    Xcode      : Xcode 8.0 Build version 8A218a 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.8 
```

**Steps to reproduce:**

Running starter command line for conference app
`ionic start test conference`
then add android platform with:
```
npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest
ionic cordova platform add android
```
Then run
```
ionic cordova emulate android
ionic cordova build android
```
Everything seems to be fine until here... emulate and build were successful but when the emulator comes up and launch the app, it looks like 
<img width="464" alt="captura de pantalla 2017-05-31 a las 11 13 27 p m" src="https://cloud.githubusercontent.com/assets/4486150/26664419/252aa002-4657-11e7-8bae-4b3048fc0d5c.png">

And trying to install the apk generated in the build command, it fails in many devices I have tred.

For iOS everything goes fine and also working with other starters projects, android works good.

Thanks for your help,
Regards

**Comment by McEwenTito** [comment] 2017-06-01 12:25
Hi, My name is McEwen Tito.

I am practicing ionic on the ionic-conference-app and am loving it, great
app. I have been looking for a way to segment the schedule into three days.
But I can't seem to figure it out. Any help rendered will be appreciated.

Thanks and best regards.

**Comment by mautematico** [comment] 2017-06-01 14:02
@McEwenTito your request is not a bug report nor a feature request, please move it to ionic forum: https://forum.ionicframework.com/

**Comment by refaelgold** [comment] 2017-06-01 15:11
Its happened  to me too . 

i will give more information about OS and emulator

i use mac OS latest 
emulator i try with 7.0 and with 7.1 and with 7.1.1 
i use Ionic CLI 3.3 and make a fresh clone when i run it 
latest Android IDE

Its works on ios perfectly

**Comment by refaelgold** [comment] 2017-06-20 10:47
Any news about it?

**Comment by mhartington** [comment] 2017-06-21 19:52
Im unable to replicate using the latest code from master. I'm going to close this, but if you're still running into issues, please open a *new* issue.

**Closed by mhartington** 2017-06-21 19:52 UTC
Labels: needs device testing
