### ISSUE TITLE
scss not compiling on core branch 

### ISSUE THREAD

**Issue by lander854** [ionic-team/ionic-conference-app#564] opened 2018-05-23 16:54 UTC
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
variables such as $tabs-ios-tab-text-color-active do not change apearence on ionic tabs

**Expected behavior:**
selected tab should change color
**Steps to reproduce:**
just clone then set  $tabs-ios-tab-text-color-active on variables.scss

**Comment by brandyscarney** [comment] 2018-05-23 17:02
Thanks for the issue! The core branch is using Ionic Framework v4. We have moved away from using Sass to customize Ionic and are now using css variables. An early preview of the documentation can be found here: https://ionic-docs.herokuapp.com/docs/theming/basics

An example of changing the theme to Oceanic: https://github.com/ionic-team/ionic/blob/master/core/src/themes/css/oceanic.css

We're hoping to have the theming more stable by next week, which will push us close to a beta release of v4. I'm going to close this since it is working as intended. 🙂

**Closed by brandyscarney** 2018-05-23 17:02 UTC
