### ISSUE TITLE
DatePicker min value

### ISSUE THREAD

**Issue by Smoke1987** [ionic-team/ionic-conference-app#418] opened 2017-06-06 12:13 UTC
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Hello! There is an element - `<ion-datetime>`. When setting the minimum value by adding the attribute `min = "2017-06-06" ` (for example), the following behavior is observed: 1) When you open the picker, and select a date, for example, "2017-07-04" (format -"YYYY-MM-DD"), and press "Accept" - the date is selected, there is nothing strange here, because `max ="2103-12-31"` (for example) 2) When you reopen picker (date value - "2017-07-04"), drag the value of the "month" one position back (previous month), click "accept" - the date is selected !!! Strange is that the date value becomes "2017-06-04"? Why? If the minimum value Does not exist `min ="2017-06-06"` ???
This behavior is NOT observed, if you re-open the picker, drag the value of the "month" one position forward, then back - then the min value constraint is triggered. More precisely - automatically resets the value to min value only from the second event of changing the date in the open picker.

**Expected behavior:**
--

**Steps to reproduce:**
--

**Related code:**
--

**Other information:**
I think, instead of enrolling in a beta tester Ionic? ))

**Ionic info:**

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by brandyscarney** [comment] 2017-06-21 14:55
Thanks for the issue! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/12070 since this is more of a framework bug, not a bug with the conference app. I was able to reproduce this.

**Closed by brandyscarney** 2017-06-21 14:55 UTC
